import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar/Navbar";
import InvoiceArea from "../components/InvoiceArea/InvoiceArea";
import { Heading, Text, Box, Center, Flex, Divider } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Invoice maker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Flex alignItems={"center"} justifyContent={"center"}>
          <Flex flexDirection={"column"} textAlign={"center"} color={"black"}>
            <Text
              bgGradient="linear(to-l, blue.300, blue.500)"
              bgClip="text"
              fontSize="5xl"
              fontWeight="extrabold"
            >
              Invoice Maker
            </Text>
            <Text
              fontSize="xl"
              bgGradient="linear(to-l, blue.300, blue.500)"
              bgClip="text"
            >
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Voluptatem, reiciendis.
            </Text>
          </Flex>
        </Flex>
        <Divider />
        <InvoiceArea />
        <Divider />
      </main>
    </>
  );
}
